import Link from "next/link";
import { asc, eq, or, isNull } from "drizzle-orm";
import { db } from "@/lib/db";
import { exercises, routines, routineSteps } from "@/lib/db/schema";
import { addRoutineStepAction, deleteRoutineAction, duplicateRoutineAction, removeRoutineStepAction } from "@/lib/routines/actions";
import { getCurrentUser } from "@/lib/auth/session";

export default async function RoutineDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const user = await getCurrentUser();
  const routine = (await db.select().from(routines).where(eq(routines.id, id)).limit(1))[0];
  if (!routine) return <main className="p-6">Rutina no encontrada</main>;
  const canEdit = !!user && !routine.isDefault && routine.userId === user.id;
  const steps = await db.select({ step: routineSteps, exercise: exercises }).from(routineSteps).leftJoin(exercises, eq(routineSteps.exerciseId, exercises.id)).where(eq(routineSteps.routineId, id)).orderBy(asc(routineSteps.order));
  const availableExercises = user ? await db.select().from(exercises).where(or(eq(exercises.isDefault, true), eq(exercises.userId, user.id), isNull(exercises.userId))).limit(80) : [];
  return <main className="mx-auto min-h-screen max-w-md px-4 py-8"><p className="text-sm font-bold text-primary-dark">{routine.category}</p><h1 className="font-serif text-4xl font-semibold">{routine.name}</h1><p className="mt-2 text-[#607169]">{routine.description}</p><div className="my-5 grid grid-cols-3 gap-2 text-center"><Box value={`${routine.estimatedMinutes}`} label="min"/><Box value={`${steps.length}`} label="pasos"/><Box value={routine.difficulty === "beginner" ? "Fácil" : routine.difficulty === "advanced" ? "Avanzado" : "Medio"} label="nivel"/></div><Link href={`/app/workout?routineId=${routine.id}`} className="block rounded-2xl bg-[#23352b] py-4 text-center font-bold text-white">Empezar</Link><div className="mt-3 grid grid-cols-2 gap-2"><form action={duplicateRoutineAction}><input type="hidden" name="routineId" value={routine.id}/><button className="w-full rounded-2xl bg-white/80 py-3 font-bold text-primary-dark ring-1 ring-black/5">Duplicar</button></form>{canEdit && <form action={deleteRoutineAction}><input type="hidden" name="routineId" value={routine.id}/><button className="w-full rounded-2xl bg-red-50 py-3 font-bold text-red-700">Eliminar</button></form>}</div>{canEdit && <form action={addRoutineStepAction} className="mt-5 space-y-3 rounded-[2rem] bg-white/80 p-5 shadow-sm ring-1 ring-black/5"><input type="hidden" name="routineId" value={routine.id}/><h2 className="font-bold">Añadir ejercicio</h2><select name="exerciseId" className="w-full rounded-2xl bg-[#f8faf7] px-4 py-3">{availableExercises.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><div className="grid grid-cols-3 gap-2"><select name="mode" className="rounded-2xl bg-[#f8faf7] px-3 py-3"><option value="time">Tiempo</option><option value="reps">Reps</option></select><input name="value" type="number" min="1" defaultValue="30" className="rounded-2xl bg-[#f8faf7] px-3 py-3"/><input name="restSeconds" type="number" min="0" defaultValue="15" className="rounded-2xl bg-[#f8faf7] px-3 py-3"/></div><button className="w-full rounded-2xl bg-[#e8f2ea] py-3 font-bold text-primary-dark">Añadir paso</button></form>}<section className="mt-6 space-y-3">{steps.map(({ step, exercise }) => <article key={step.id} className="rounded-2xl bg-white/80 p-4 shadow-sm ring-1 ring-black/5"><div className="flex gap-2"><div className="flex-1"><p className="font-bold">{step.order}. {exercise?.name}</p><p className="text-sm text-[#607169]">{step.mode === "time" ? `${step.value} segundos` : `${step.value} repeticiones`} · descanso {step.restSeconds}s</p></div>{canEdit && <form action={removeRoutineStepAction}><input type="hidden" name="routineId" value={routine.id}/><input type="hidden" name="stepId" value={step.id}/><button className="text-sm font-bold text-red-700">Quitar</button></form>}</div><details className="mt-2 text-sm text-[#607169]"><summary className="font-bold text-primary-dark">Instrucciones</summary>{exercise?.instructions}</details></article>)}</section></main>;
}
function Box({value,label}:{value:string;label:string}){return <div className="rounded-2xl bg-white/80 p-3"><p className="text-xl font-bold">{value}</p><p className="text-sm text-[#607169]">{label}</p></div>}
